== Reference System

This system defines the rules for referencing members in the code
based on the relationship between containers and members.
Referencing a member doesn't guarantees the access to it,
the access to the members is managed by the <<Access System>>.

Since all members have a <<Naming Rules,name>>, containers can be viewed as a list of names and each name
could contain more names since some members are containers too.
This structure of names is delimited by following rules:

* A member cannot be defined in a container if the container or any of its parents have already a member with the same name,
this results in <<Shadowing Disallowance>>.
* In a given container, any name defined in the container or any of its parents is available to be referenced.
* A member can be referenced by using the <<Member Path>> as long as the first name of the path is available to be referenced.
* The names defined in a container without name like <<source-file,Source Files>>, are assumed by its parent container.
* Given two containers with name that are siblings, the members defined in each container are not available to be referenced in each other.

=== Naming Rules

Any name can be given to a member, but the way to represent the names in the Bm Language obbey two formats:

* One letter followed by more letters or digits.
* Delimited string using grave accent (```).

The characters that are considered letters are
from `a` to `z` (lowercase), from `A` to `Z` (uppercase), `_` (underscore), `$` (dollar sign) and `@` (at symbol).
The delimited string follows the <<Character Escaping>> rules.

=== Member Path

Since the name of a member is unique, members can be referenced unambiguously using the member path
which can be generated by joining the path of the container and the name of the member with a point (`.`),
containers without name are ignored.

.Member Path example
[source,bm]
----
                                        // Member Path:
module math {                           // "math"
  let PI = 3.141592;                    // "math.PI"
  function max(a int, b int) int {      // "math.max"
    return a > b ? a : b;
  }
  module geo {                          // "math.geo"
    function tan(value double) double { // "math.geo.tan"
      // fancy maths...
    }
  }
}
----

=== Shadowing Disallowance

Naming a member with the same name than a member that can be referenced is not allowed because it generates ambiguity.

[source,bm]
----
let x = 0;

class Point {
  var x = 0; // ERROR: The member "x" is already defined in the parent module.
  var y = 0;

  function moveTo(@x, y) { // ERROR: The member "y" is already defined in the class "Point".
    let Point = null; // ERROR: The member "Point" is already defined in the parent module.
  }
}
----

