== Access System

This system refers to how the members are accessed through the modules.
This is controlled by using a set of keywords called access modifiers
which define the rules to access to some member from a certain module.

.How access modifiers work
[cols="40,15,15,15,15"]
|===
|Who can access to the member? | `protect` | _(default)_ | `share` | `export`

|Same declaring container          | ✅ | ✅ | ✅ | ✅
|Same module in the same suite     | ❌ | ✅ | ✅ | ✅
|Any module in the same suite      | ❌ | ❌ | ✅ | ✅
|Any module in any suite           | ❌ | ❌ | ❌ | ✅

|===

=== Protect Modifier

The `protect` modifier is the most secure modifier, the access to members declared with this modifier
is limited only to the container where the member was declared,
they can't be imported or accessed by other source files.

.file1.bm
[source,bm]
----
class Foo {
  protect let BAR = 1;
}

protect let BAZ = Foo().BAR + 1; // ERROR: `BAR` is not accessible
----

.file2.bm
[source,bm]
----
protect let QUX = BAZ + 1; // ERROR: `BAZ` is not accessible

module abc {
  let XYZ = QUX + 1; // OK! `QUX` is accessible
}
----

=== Default Modifier

The _default_ modifier is the most handy modifier,
to declare a member with this kind of access the member shouldn't have an access modifier at all.

This modifier makes that the member can be accessed only by
the members defined in the same module or submodules of the same suite,
other modules can't import or referencing the member.
It keeps being secure, in the sense that it encapsulates the member in the declaring module.


.file1.bm
[source,bm]
----
let FOO = 1;
----

.file2.bm
[source,bm]
----
module bar {
  let BAZ = FOO + 1; // OK! `FOO` is accessible
}
let QUX = bar.BAZ + 1; // ERROR: `BAZ` is not accessible
----

=== Share Modifier

The `share` modifier has two behaviours depending on the member:

* Class members: allows the member to be available in any subclass no matter the suite.
* Other members: allows the importing and referencing of the member across the suite.

.file1.bm
[source,bm]
----
module debug {
  share function log(message String) { /* ... */ }
}
----

.file2.bm
[source,bm]
----
module foo {
  import debug.log;

  function bar() {
    log("bar..."); // OK! `log` is accessible
  }
}
----

=== Export Modifier

The `export` modifier should only be used when the member needs to be exported outside the suite.
Members declared in the same module or submodules have access to the declared member without importing it
and the member can be imported in any module of any suite.

.Suite 1 (foobar)
[source,bm]
----
export function foo() { /* ... */ }

share function bar() { /* ... */ }
----

.Suite 2 (barqux)
[source,bm]
----
import foobar.foo; // OK! `foo` is exported
import foobar.bar; // ERROR! `bar` is not exported
----
