== Structure

Bm has a simple structure to organize the logic: Members and Containers.
Some containers are also members and some members only contain logic.

|===
|Item|Is Container?|Is Member?|Only logic?

|<<source-file,Source File>>  |✅|❌|❌
|<<Modules,Module>>           |✅|✅|❌
|<<Classes,Class>>            |✅|✅|❌
|<<Interfaces,Interface>>     |✅|✅|❌
|<<Enums,Enum>>               |✅|✅|❌
|<<Lambdas,Lambda>>           |❌|✅|❌
|<<Fields,Field>>             |❌|✅|❌
|<<Imports,Import>>           |❌|✅|❌
|<<Functions,Function>>       |❌|✅|✅
|<<Properties,Property>>      |❌|✅|✅
|<<Operators,Operator>>       |❌|✅|✅
|<<Constructors,Constructor>> |❌|✅|✅

|===

=== Members

A member represents an unique named item that belongs to a container,
however, some members can be composed by more than one definition:

* <<Functions>>, <<Constructors>> and <<Operators>>:
since the <<Overloading>> of a member is allowed, each overload counts as one definition that composes the same member.
* <<Properties>>: a `getter` or `setter` definitions with the same name in a container, compose a single property.
* <<Modules>>: all module definitions with the same <<member-path,Member Path>> found in a suite, compose the same module.

=== Containers

The containers are used to group members, all members have an owner which must be a container
(the <<Global Module>> is the only member that doesn't have owner since it is the root).

The owner of a member is not necessarily the container where it was defined:

* The [#source-file]#*Source Files*# are containers but the actual owner of the members defined inside is the
<<Implicit Modules,Implicit Module>> which represents the directory of the file.
* When <<Imports,importing>> a member, the actual owner of the member is where is was first defined,
the owner doesn't change becase it was imported into another module.

The fact that the containers can hold members already defined in other containers helps to build the <<Reference System>>.

.Relationship between containers and members which can own
[cols="20,80"]
|===
|Container|Members

|<<Modules,Module>>
|<<Classes,Class>>,
 <<Interfaces,Interface>>,
 <<Functions,Function>>,
 <<Fields,Field>>,
 <<Properties,Property>>,
 <<Lambdas,Lambda>>,
 <<Enums,Enum>>,
 <<Imports,Import>>,
 <<Modules,Module>>

|<<Classes,Class>>
|<<Fields,Field>>,
 <<Properties,Property>>,
 <<Functions,Function>>,
 <<Operators,Operator>>,
 <<Constructors,Constructor>>

|<<Interfaces,Interface>>
|<<Fields,Field>>,
 <<Functions,Function>>,
 <<Operators,Operator>>

|<<Enums,Enum>>
|<<Fields,Field>>
|===


