= Functions

Functions are invocable blocks of code which can receive arguments and optionally produce a result.

Only when the function has a return type specifed, the function must use the `return` statement
to complete the execution with a result.

Functions can be only owned by following members and the way to invoke them will depend on the owner:

* <<Modules>>: Functions can be invoked directly.
* <<Classes>>: Functions can only invoked through an instance.

[source,bm]
----
function abs(n Number) Number {
  return n < 0 ? -n : n;
}

class Rectangle {
  var width = 0.0;
  var height = 0.0;

  constructor new(@width int, @height int) {
    width = @width;
    height = @height;
  }

  function computeArea() float {
    return width * height;
  }
}

function main() {
  // module functions can be invoked directly
  console.log(abs(-1));             // output: 1

  // class functions need an instance to be invoked
  let rect = Rectangle.new(10, 20);
  console.log(rect.computeArea());  // output: 200
}
----

== Function Parameters

Functions can receive any number of parameters which are considered as fields available only during the function execution.

In order to improve readability, the keywords `var` and `let` are optional when declaring parameters and it is defaulted to `let`.

Since parameters are passed by <<References,reference>>, reassignments only affects the reference in the function's body.

[source,bm]
----
function test(name String, var index int!) {
  name = "Mat";      // ERROR: The field can't be reasigned
  index = index + 1; // OK! the field is explicitly `var`
}
----

== Optional parameters

Optional parameters are allowed by specifying the initial value when declaring them.
Any parameter can be optional no matter the order, however, when invoking the function
sending a list of arguments, optional parameters can't be skipped.
The only way to skip an optional parameter is by invoking the function
using <<Named Arguments>>.

It doesn't matter if the optional parameter is `let` or `var`, the initial value
specified in the parameter declaration is only used when there is no value specified
in the function invocation.

[source,bm]
----
function write(data List<byte>, offset int! = 0, length int = null) {
  // ...
}

function test() {
  let data = [1, 2, 3];     // Optional arguments received:
  write(data);              //  offset = 0, length = null
  write(data, 1);           //  offset = 1, length = null
  write(data, 1, 2);        //  offset = 1, length = 2
  write(data, length: 2);   //  offset = 0, length = 2
}
----
